<?php

namespace App\Exceptions;

use App\ultis\toast\Toaster;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    public function render($request, Throwable $e): \Symfony\Component\HttpFoundation\Response
    {

        if ($e instanceof ShouldToastException) {
            Toaster::toast($e->getMessage(), $e->getToastType());
            redirect()
                ->back();
            return new Response();
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

}
